DEV_ID: [0,]
IMG_DIR: ""
VIDEO_FILE: ""
RTSP_URL: ""

DEBUG: True
SRC_TYPE: 3 # 0-IMGS 1-VIDEO 2-RTSP 3-HTTP POST IMG
RUN_MODE: "service" # "single" "batch" "batch_thread" "service"

DETECTOR: # 检测模型
    TYPE: "coco_detector"
    NAME: 'yolov34'
    PRODUCER_NAME: 'sophon'
    ENGINE_FILE: '../data/models/yolov4_608_coco_fp32_1b.bmodel'
    LABEL_FILE: '../data/coco.names'
    DEV_ID: 0

    YOLO_MASKS: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    YOLO_ANCHORS: [12, 16, 19, 36, 40, 28, 36, 75,
                    76, 55, 72, 146, 142, 110, 192, 243, 459, 401]
    
    OUTPUT_TENSOR_CHANNELS: [76, 38, 19]
    MIN_CONFIDENCE: 0.5
    NMS_MAX_OVERLAP: 0.45
