DEV_ID: [0,]
IMG_DIR: ""
VIDEO_FILE: ""
RTSP_URL: ""

DEBUG: True
SRC_TYPE: 3 # 0-IMGS 1-VIDEO 2-RTSP 3-HTTP POST IMG
RUN_MODE: "service" # "single" "batch" "batch_thread" "service"

DETECTOR: # 检测模型
    TYPE: "coco_detector"
    NAME: 'yolov34'
    PRODUCER_NAME: 'sophon'
    ENGINE_FILE: '../data/models/yolov3_416_coco_fp32_1b.bmodel'
    LABEL_FILE: '../data/coco.names'
    DEV_ID: 0

    YOLO_MASKS: [6, 7, 8, 3, 4, 5, 0, 1, 2]
    YOLO_ANCHORS: [10, 13, 16, 30, 33, 23, 30, 61, 62, 45,
                    59, 119, 116, 90, 156, 198, 373, 326]
    
    OUTPUT_TENSOR_CHANNELS: [13, 26, 52]
    MIN_CONFIDENCE: 0.5
    NMS_MAX_OVERLAP: 0.45
